package com.chao.frame.user.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ATK001
     *
     * @mbg.generated
     */
    private Long atk001;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ATC002
     *
     * @mbg.generated
     */
    private String atc002;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ATC003
     *
     * @mbg.generated
     */
    private String atc003;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ATC004
     *
     * @mbg.generated
     */
    private Date atc004;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ATC005
     *
     * @mbg.generated
     */
    private Integer atc005;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ATC006
     *
     * @mbg.generated
     */
    private Integer atc006;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public User(Long atk001, String atc002, String atc003, Date atc004, Integer atc005, Integer atc006) {
        this.atk001 = atk001;
        this.atc002 = atc002;
        this.atc003 = atc003;
        this.atc004 = atc004;
        this.atc005 = atc005;
        this.atc006 = atc006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ATK001
     *
     * @return the value of user.ATK001
     *
     * @mbg.generated
     */
    public Long getAtk001() {
        return atk001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ATC002
     *
     * @return the value of user.ATC002
     *
     * @mbg.generated
     */
    public String getAtc002() {
        return atc002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ATC003
     *
     * @return the value of user.ATC003
     *
     * @mbg.generated
     */
    public String getAtc003() {
        return atc003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ATC004
     *
     * @return the value of user.ATC004
     *
     * @mbg.generated
     */
    public Date getAtc004() {
        return atc004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ATC005
     *
     * @return the value of user.ATC005
     *
     * @mbg.generated
     */
    public Integer getAtc005() {
        return atc005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ATC006
     *
     * @return the value of user.ATC006
     *
     * @mbg.generated
     */
    public Integer getAtc006() {
        return atc006;
    }
}