package com.chao.frame.user.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andAtk001IsNull() {
            addCriterion("ATK001 is null");
            return (Criteria) this;
        }

        public Criteria andAtk001IsNotNull() {
            addCriterion("ATK001 is not null");
            return (Criteria) this;
        }

        public Criteria andAtk001EqualTo(Long value) {
            addCriterion("ATK001 =", value, "atk001");
            return (Criteria) this;
        }

        public Criteria andAtk001NotEqualTo(Long value) {
            addCriterion("ATK001 <>", value, "atk001");
            return (Criteria) this;
        }

        public Criteria andAtk001GreaterThan(Long value) {
            addCriterion("ATK001 >", value, "atk001");
            return (Criteria) this;
        }

        public Criteria andAtk001GreaterThanOrEqualTo(Long value) {
            addCriterion("ATK001 >=", value, "atk001");
            return (Criteria) this;
        }

        public Criteria andAtk001LessThan(Long value) {
            addCriterion("ATK001 <", value, "atk001");
            return (Criteria) this;
        }

        public Criteria andAtk001LessThanOrEqualTo(Long value) {
            addCriterion("ATK001 <=", value, "atk001");
            return (Criteria) this;
        }

        public Criteria andAtk001In(List<Long> values) {
            addCriterion("ATK001 in", values, "atk001");
            return (Criteria) this;
        }

        public Criteria andAtk001NotIn(List<Long> values) {
            addCriterion("ATK001 not in", values, "atk001");
            return (Criteria) this;
        }

        public Criteria andAtk001Between(Long value1, Long value2) {
            addCriterion("ATK001 between", value1, value2, "atk001");
            return (Criteria) this;
        }

        public Criteria andAtk001NotBetween(Long value1, Long value2) {
            addCriterion("ATK001 not between", value1, value2, "atk001");
            return (Criteria) this;
        }

        public Criteria andAtc002IsNull() {
            addCriterion("ATC002 is null");
            return (Criteria) this;
        }

        public Criteria andAtc002IsNotNull() {
            addCriterion("ATC002 is not null");
            return (Criteria) this;
        }

        public Criteria andAtc002EqualTo(String value) {
            addCriterion("ATC002 =", value, "atc002");
            return (Criteria) this;
        }

        public Criteria andAtc002NotEqualTo(String value) {
            addCriterion("ATC002 <>", value, "atc002");
            return (Criteria) this;
        }

        public Criteria andAtc002GreaterThan(String value) {
            addCriterion("ATC002 >", value, "atc002");
            return (Criteria) this;
        }

        public Criteria andAtc002GreaterThanOrEqualTo(String value) {
            addCriterion("ATC002 >=", value, "atc002");
            return (Criteria) this;
        }

        public Criteria andAtc002LessThan(String value) {
            addCriterion("ATC002 <", value, "atc002");
            return (Criteria) this;
        }

        public Criteria andAtc002LessThanOrEqualTo(String value) {
            addCriterion("ATC002 <=", value, "atc002");
            return (Criteria) this;
        }

        public Criteria andAtc002Like(String value) {
            addCriterion("ATC002 like", value, "atc002");
            return (Criteria) this;
        }

        public Criteria andAtc002NotLike(String value) {
            addCriterion("ATC002 not like", value, "atc002");
            return (Criteria) this;
        }

        public Criteria andAtc002In(List<String> values) {
            addCriterion("ATC002 in", values, "atc002");
            return (Criteria) this;
        }

        public Criteria andAtc002NotIn(List<String> values) {
            addCriterion("ATC002 not in", values, "atc002");
            return (Criteria) this;
        }

        public Criteria andAtc002Between(String value1, String value2) {
            addCriterion("ATC002 between", value1, value2, "atc002");
            return (Criteria) this;
        }

        public Criteria andAtc002NotBetween(String value1, String value2) {
            addCriterion("ATC002 not between", value1, value2, "atc002");
            return (Criteria) this;
        }

        public Criteria andAtc003IsNull() {
            addCriterion("ATC003 is null");
            return (Criteria) this;
        }

        public Criteria andAtc003IsNotNull() {
            addCriterion("ATC003 is not null");
            return (Criteria) this;
        }

        public Criteria andAtc003EqualTo(String value) {
            addCriterion("ATC003 =", value, "atc003");
            return (Criteria) this;
        }

        public Criteria andAtc003NotEqualTo(String value) {
            addCriterion("ATC003 <>", value, "atc003");
            return (Criteria) this;
        }

        public Criteria andAtc003GreaterThan(String value) {
            addCriterion("ATC003 >", value, "atc003");
            return (Criteria) this;
        }

        public Criteria andAtc003GreaterThanOrEqualTo(String value) {
            addCriterion("ATC003 >=", value, "atc003");
            return (Criteria) this;
        }

        public Criteria andAtc003LessThan(String value) {
            addCriterion("ATC003 <", value, "atc003");
            return (Criteria) this;
        }

        public Criteria andAtc003LessThanOrEqualTo(String value) {
            addCriterion("ATC003 <=", value, "atc003");
            return (Criteria) this;
        }

        public Criteria andAtc003Like(String value) {
            addCriterion("ATC003 like", value, "atc003");
            return (Criteria) this;
        }

        public Criteria andAtc003NotLike(String value) {
            addCriterion("ATC003 not like", value, "atc003");
            return (Criteria) this;
        }

        public Criteria andAtc003In(List<String> values) {
            addCriterion("ATC003 in", values, "atc003");
            return (Criteria) this;
        }

        public Criteria andAtc003NotIn(List<String> values) {
            addCriterion("ATC003 not in", values, "atc003");
            return (Criteria) this;
        }

        public Criteria andAtc003Between(String value1, String value2) {
            addCriterion("ATC003 between", value1, value2, "atc003");
            return (Criteria) this;
        }

        public Criteria andAtc003NotBetween(String value1, String value2) {
            addCriterion("ATC003 not between", value1, value2, "atc003");
            return (Criteria) this;
        }

        public Criteria andAtc004IsNull() {
            addCriterion("ATC004 is null");
            return (Criteria) this;
        }

        public Criteria andAtc004IsNotNull() {
            addCriterion("ATC004 is not null");
            return (Criteria) this;
        }

        public Criteria andAtc004EqualTo(Date value) {
            addCriterionForJDBCDate("ATC004 =", value, "atc004");
            return (Criteria) this;
        }

        public Criteria andAtc004NotEqualTo(Date value) {
            addCriterionForJDBCDate("ATC004 <>", value, "atc004");
            return (Criteria) this;
        }

        public Criteria andAtc004GreaterThan(Date value) {
            addCriterionForJDBCDate("ATC004 >", value, "atc004");
            return (Criteria) this;
        }

        public Criteria andAtc004GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ATC004 >=", value, "atc004");
            return (Criteria) this;
        }

        public Criteria andAtc004LessThan(Date value) {
            addCriterionForJDBCDate("ATC004 <", value, "atc004");
            return (Criteria) this;
        }

        public Criteria andAtc004LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ATC004 <=", value, "atc004");
            return (Criteria) this;
        }

        public Criteria andAtc004In(List<Date> values) {
            addCriterionForJDBCDate("ATC004 in", values, "atc004");
            return (Criteria) this;
        }

        public Criteria andAtc004NotIn(List<Date> values) {
            addCriterionForJDBCDate("ATC004 not in", values, "atc004");
            return (Criteria) this;
        }

        public Criteria andAtc004Between(Date value1, Date value2) {
            addCriterionForJDBCDate("ATC004 between", value1, value2, "atc004");
            return (Criteria) this;
        }

        public Criteria andAtc004NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ATC004 not between", value1, value2, "atc004");
            return (Criteria) this;
        }

        public Criteria andAtc005IsNull() {
            addCriterion("ATC005 is null");
            return (Criteria) this;
        }

        public Criteria andAtc005IsNotNull() {
            addCriterion("ATC005 is not null");
            return (Criteria) this;
        }

        public Criteria andAtc005EqualTo(Integer value) {
            addCriterion("ATC005 =", value, "atc005");
            return (Criteria) this;
        }

        public Criteria andAtc005NotEqualTo(Integer value) {
            addCriterion("ATC005 <>", value, "atc005");
            return (Criteria) this;
        }

        public Criteria andAtc005GreaterThan(Integer value) {
            addCriterion("ATC005 >", value, "atc005");
            return (Criteria) this;
        }

        public Criteria andAtc005GreaterThanOrEqualTo(Integer value) {
            addCriterion("ATC005 >=", value, "atc005");
            return (Criteria) this;
        }

        public Criteria andAtc005LessThan(Integer value) {
            addCriterion("ATC005 <", value, "atc005");
            return (Criteria) this;
        }

        public Criteria andAtc005LessThanOrEqualTo(Integer value) {
            addCriterion("ATC005 <=", value, "atc005");
            return (Criteria) this;
        }

        public Criteria andAtc005In(List<Integer> values) {
            addCriterion("ATC005 in", values, "atc005");
            return (Criteria) this;
        }

        public Criteria andAtc005NotIn(List<Integer> values) {
            addCriterion("ATC005 not in", values, "atc005");
            return (Criteria) this;
        }

        public Criteria andAtc005Between(Integer value1, Integer value2) {
            addCriterion("ATC005 between", value1, value2, "atc005");
            return (Criteria) this;
        }

        public Criteria andAtc005NotBetween(Integer value1, Integer value2) {
            addCriterion("ATC005 not between", value1, value2, "atc005");
            return (Criteria) this;
        }

        public Criteria andAtc006IsNull() {
            addCriterion("ATC006 is null");
            return (Criteria) this;
        }

        public Criteria andAtc006IsNotNull() {
            addCriterion("ATC006 is not null");
            return (Criteria) this;
        }

        public Criteria andAtc006EqualTo(Integer value) {
            addCriterion("ATC006 =", value, "atc006");
            return (Criteria) this;
        }

        public Criteria andAtc006NotEqualTo(Integer value) {
            addCriterion("ATC006 <>", value, "atc006");
            return (Criteria) this;
        }

        public Criteria andAtc006GreaterThan(Integer value) {
            addCriterion("ATC006 >", value, "atc006");
            return (Criteria) this;
        }

        public Criteria andAtc006GreaterThanOrEqualTo(Integer value) {
            addCriterion("ATC006 >=", value, "atc006");
            return (Criteria) this;
        }

        public Criteria andAtc006LessThan(Integer value) {
            addCriterion("ATC006 <", value, "atc006");
            return (Criteria) this;
        }

        public Criteria andAtc006LessThanOrEqualTo(Integer value) {
            addCriterion("ATC006 <=", value, "atc006");
            return (Criteria) this;
        }

        public Criteria andAtc006In(List<Integer> values) {
            addCriterion("ATC006 in", values, "atc006");
            return (Criteria) this;
        }

        public Criteria andAtc006NotIn(List<Integer> values) {
            addCriterion("ATC006 not in", values, "atc006");
            return (Criteria) this;
        }

        public Criteria andAtc006Between(Integer value1, Integer value2) {
            addCriterion("ATC006 between", value1, value2, "atc006");
            return (Criteria) this;
        }

        public Criteria andAtc006NotBetween(Integer value1, Integer value2) {
            addCriterion("ATC006 not between", value1, value2, "atc006");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}